---
- name: Kubeconfig / kubectl access check
  command: kubectl cluster-info
  register: kubectl_check
  ignore_errors: true
  changed_when: false
  check_mode: false

- name: "Kubernetes client/server version (When: kubectl access is required)"
  command: kubectl version --output=yaml
  register: kubectl_version
  when: kubectl_check.rc == 0
  changed_when: false
  ignore_errors: true
  check_mode: false

- name: kubeadm version
  command: kubeadm version -o short
  register: kubeadm_version
  ignore_errors: true
  changed_when: false
  check_mode: false

- name: kubelet version
  command: kubelet --version
  register: kubelet_version
  ignore_errors: true
  changed_when: false
  check_mode: false

- name: containerd version
  command: containerd --version
  register: containerd_version
  ignore_errors: true
  changed_when: false
  check_mode: false

- name: runc version
  command: runc --version
  register: runc_version
  ignore_errors: true
  changed_when: false
  check_mode: false

- name: "etcd image/version info (When: kubectl access is required)"
  command: kubectl get pods -n kube-system -l component=etcd -o jsonpath={.items[0].spec.containers[0].image}
  register: etcd_version
  when: kubectl_check.rc == 0
  changed_when: false
  ignore_errors: true
  check_mode: false
