[master]
192.168.1.10 ansible_user=ubuntu ansible_ssh_pass=GizliSifre123 ansible_become_pass=GizliSifre123

[singlenode]
192.168.1.11 ansible_user=ubuntu ansible_ssh_pass=GizliSifre123 ansible_become_pass=GizliSifre123

[worker1]
192.168.1.21 ansible_user=ubuntu ansible_ssh_pass=GizliSifre123 ansible_become_pass=GizliSifre123

[worker2]
192.168.1.22 ansible_user=ubuntu ansible_ssh_pass=GizliSifre123 ansible_become_pass=GizliSifre123

[worker3]
192.168.1.23 ansible_user=ubuntu ansible_ssh_pass=GizliSifre123 ansible_become_pass=GizliSifre123

[workers:children]
worker1
worker2
worker3

[datanode]
192.168.1.30 ansible_user=ubuntu ansible_ssh_pass=GizliSifre123 ansible_become_pass=GizliSifre123
