---
- name: Kubernetes Control-Plane Güncellemesi (kubeadm upgrade apply/node)
  hosts: master:singlenode
  serial: 1
  gather_facts: false

  vars:
    first_control_plane: "{{ (groups['master'] | default([]) + groups['singlenode'] | default([])) | first }}"

  pre_tasks:
    - name: Ping pong bağlantı testi
      import_tasks: tasks/ping_pong.yml

    - name: Hedef Kubernetes sürüm girdisini doğrula
      import_tasks: tasks/validate_kube_version.yml

  tasks:
    - name: Node güncelleme adımlarını çalıştır
      import_tasks: tasks/k8s_upgrade_node.yml

- name: Kubernetes Worker Node Güncellemesi (kubeadm upgrade node)
  hosts: workers
  serial: 1
  gather_facts: false

  vars:
    first_control_plane: "{{ (groups['master'] | default([]) + groups['singlenode'] | default([])) | first }}"

  pre_tasks:
    - name: Ping pong bağlantı testi
      import_tasks: tasks/ping_pong.yml

    - name: Hedef Kubernetes sürüm girdisini doğrula
      import_tasks: tasks/validate_kube_version.yml

  tasks:
    - name: Node güncelleme adımlarını çalıştır
      import_tasks: tasks/k8s_upgrade_node.yml
