---
- name: Host container image inventory
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: Ping connectivity test
      import_tasks: tasks/ping_pong.yml

  tasks:
    - name: Collect and report image inventory
      import_tasks: tasks/container_images_inventory.yml
