---
- name: TLS / Ingress / Kubernetes certificate check
  hosts: master:singlenode
  gather_facts: true
  environment:
    KUBECONFIG: "{{ '/root/.kube/config' if ansible_user == 'root' else '/home/' ~ ansible_user ~ '/.kube/config' }}"

  vars:
    first_control_plane: "{{ (groups['master'] | default([]) + groups['singlenode'] | default([])) | first }}"

  pre_tasks:
    - name: Ping connectivity test
      import_tasks: tasks/ping_pong.yml

  tasks:
    - name: Generate certificate / Ingress TLS report
      become: true
      script: k8s_tls_certificates_check.py
      args:
        executable: python3
      register: tls_report
      changed_when: false
      ignore_errors: true
      check_mode: false
      when: inventory_hostname == first_control_plane

    - name: TLS / Ingress / K8s certificate report
      debug:
        msg: >-
          {{
            ['#' * 80,
             '# HOST: ' ~ inventory_hostname,
             '# hostname: ' ~ (ansible_facts['hostname'] | default('n/a')),
             '#' * 80]
            + (tls_report.stdout_lines
               | default(tls_report.stderr_lines | default(['Report could not be generated'])))
          }}
      when: inventory_hostname == first_control_plane
