---
- name: Storage / inode / PV health report
  hosts: all
  gather_facts: true
  environment:
    KUBECONFIG: "{{ '/root/.kube/config' if ansible_user == 'root' else '/home/' ~ ansible_user ~ '/.kube/config' }}"

  pre_tasks:
    - name: Ping connectivity test
      import_tasks: tasks/ping_pong.yml

  tasks:
    - name: Generate storage report
      become: true
      script: storage_health_check.py
      args:
        executable: python3
      register: storage_report
      changed_when: false
      ignore_errors: true
      check_mode: false

    - name: Storage / inode / PV report
      debug:
        msg:
          - |
            ################################################################################
            # HOST: {{ inventory_hostname }}
            # hostname: {{ ansible_facts['hostname'] | default('n/a') }}
            ################################################################################
          - "{{ storage_report.stdout | default(storage_report.stderr | default('Report could not be generated')) }}"
