---
- name: Kubernetes etcd Veritabanı Yedeği Alma
  hosts: master:singlenode
  gather_facts: true

  vars:
    first_control_plane: "{{ (groups['master'] | default([]) + groups['singlenode'] | default([])) | first }}"

  pre_tasks:
    - name: Ping pong bağlantı testi
      import_tasks: tasks/ping_pong.yml

  tasks:
    - name: etcd backup scriptini çalıştır
      become: true
      script: files/k8s_etcd_backup.sh
      register: etcd_backup_result
      changed_when: true
      when: inventory_hostname == first_control_plane

    - name: Yedekleme sonucu
      debug:
        msg:
          - |
            ################################################################################
            # HOST: {{ inventory_hostname }}
            ################################################################################
          - "{{ etcd_backup_result.stdout_lines | default(['Yedekleme sadece ilk master node üzerinde çalışır.']) }}"
